# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
np.__version__
np.show_config()

'1.18.5'

#### 3. Create a null vector of size 10 (★☆☆)

In [11]:
Z = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [13]:
Z = np.zeros(10)
mem = Z.size * Z.itemsize

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [16]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [19]:
Z = np.zeros(10)
Z[4] = 1

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [21]:
Z = np.arange(10, 50)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [25]:
Z = np.arange(1, 11)
Z = Z[::-1]

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [28]:
Z = np.arange(9).reshape(-1, 3)

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [29]:
Z = np.array([1, 2, 0, 0, 4, 0])
idx = Z.nonzero()

#### 11. Create a 3x3 identity matrix (★☆☆)

In [31]:
Z = np.eye(3)

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [33]:
Z = np.random.random((3, 3, 3))

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [37]:
Z = np.random.random((10, 10))

Zmin, Zmax = Z.min(), Z.max()

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [40]:
Z = np.random.random(30)
mean = np.mean(Z)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [45]:
Z = np.ones((10, 10))
Z[1:-1, 1:-1] = 0

print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [57]:
Z = np.ones((10,10))
X = np.pad(Z, 1)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [61]:
vec = np.arange(1, 5)
Z = np.diag(vec, k=-1)
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [63]:
Z = np.zeros((8, 8))
Z[1::2, 1::2] = 1
Z[0::2, 0::2] = 1

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [74]:
Z = np.random.random((6,7,8))
idx_100 = np.unravel_index(100, Z.shape)
Z[idx_100]

0.777072012105802

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [86]:
pattern = np.array([[0, 1],
                    [1, 0]])
Z = np.tile(pattern, (4, 4))

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [88]:
answer(22)

Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [89]:
answer(23)

color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [91]:
X = np.random.random((5, 3))
Y = np.random.random((3, 2))

Z1 = np.dot(X, Y)
Z2 = X @ Y

print(np.allclose(Z1, Z2))

True


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [96]:
Z = np.arange(1, 11)
Z[(3 < Z) & (Z < 8)] *= -1

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [98]:
X = np.arange(1, 11)
Y = np.arange(5, 16)
Z = np.intersect1d(X, Y)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [111]:
row = np.arange(0, 5)
Z = np.zeros((5, 5))
Z += row


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [118]:
def generate():
    for i in range(10):
        yield i

Z = np.fromiter(generate(), dtype=np.int)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [122]:
Z = np.linspace(0, 1, 11, endpoint=False)[1:]

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [123]:
Z = np.random.random(10)
Z.sort()

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [128]:
X, Y = np.random.random(10), np.random.random(10)
np.allclose(X, Y)
np.array_equal(X, Y)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [130]:
Z = np.zeros(10)
Z.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [131]:
Z = np.random.random(10)
idx_max = Z.argmax()
Z[idx_max] = 0

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [141]:
Z = np.zeros((5, 5), dtype= [('x', float), ('y', float)])

Z['x'], Z['y'] = np.meshgrid(np.linspace(0, 1, 5), 
                                np.linspace(0, 1, 5))

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [143]:
answer(48)

for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)


#### 49. How to print all the values of an array? (★★☆)

In [142]:
answer(49)

np.set_printoptions(threshold=float("inf"))
Z = np.zeros((16,16))
print(Z)


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [11]:
Z = np.random.random(20)
v = np.random.random(1)

index = (np.abs(Z-v)).argmin()
print(Z[index])

0.44824035536888573


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [21]:
Z = np.zeros(100, [ ('position', [('x', float, 1),
                                    ('y', float, 1)] ),
                    ( 'rgb',   [ ('r', float, 1),
                                ('g', float, 1),
                                ('b', float, 1) ] ) ] )

In [23]:
answer(51)

Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [26]:
Z = np.random.random((100, 2))

from scipy.spatial.distance import cdist

dists = cdist(Z, Z)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [35]:
Z = np.random.random(1000).astype(np.float32)
V = Z.view(np.int32)
V[:] = Z

In [32]:
answer(53)

# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
a

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [47]:
Z = np.random.random(12).reshape(-1, 3)

for index, value in np.ndenumerate(Z):
    print(f"{value} at {index}")

print("-" * 20)

for index in np.ndindex(Z.shape):
    print(f"{Z[index]} at {index}")

0.6911198080137603 at (0, 0)
0.9676856523958945 at (0, 1)
0.3760365470262904 at (0, 2)
0.6203931874326585 at (1, 0)
0.9590312644505611 at (1, 1)
0.6121596974362411 at (1, 2)
0.733734868730321 at (2, 0)
0.7918441022983063 at (2, 1)
0.7794800019550773 at (2, 2)
0.7749953229737941 at (3, 0)
0.1957253109197894 at (3, 1)
0.33582723982647356 at (3, 2)
--------------------
0.6911198080137603 at (0, 0)
0.9676856523958945 at (0, 1)
0.3760365470262904 at (0, 2)
0.6203931874326585 at (1, 0)
0.9590312644505611 at (1, 1)
0.6121596974362411 at (1, 2)
0.733734868730321 at (2, 0)
0.7918441022983063 at (2, 1)
0.7794800019550773 at (2, 2)
0.7749953229737941 at (3, 0)
0.1957253109197894 at (3, 1)
0.33582723982647356 at (3, 2)


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [2]:
answer(57)

# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)


In [4]:
n = 10
p = 3
Z = np.zeros((n, n))
np.put(Z, np.random.choice(n*n, p, replace=False), 1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [11]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[ 3.64351527e-02 -1.40379732e-01 -2.47499381e-01  1.69239599e-01
  -2.75161618e-01  3.04104435e-01 -3.24051273e-01  1.12647594e-01
   2.44995656e-01  1.19669568e-01]
 [ 2.80337176e-01  1.10134906e-01  1.56697002e-01 -1.23362484e-01
   5.88757614e-02 -3.50416976e-01  1.42930130e-01 -5.16956500e-01
   2.09934084e-01  3.18269016e-02]
 [-6.81012061e-02  1.04722759e-01  1.86972236e-01  1.49792067e-01
  -3.40373728e-04 -2.20184510e-01 -4.31321995e-01  1.85004507e-01
   2.18975845e-01 -1.25519328e-01]
 [ 2.36274627e-01  3.77653596e-01  2.43925790e-01 -4.40742404e-01
  -4.10353698e-01 -4.00282506e-01 -3.14937971e-01  1.97288108e-01
   4.40196988e-01  7.09774724e-02]
 [-2.81992276e-01  4.50515900e-02  3.55210214e-01 -3.97703417e-01
  -6.39470931e-02  1.52316309e-01  1.55901781e-01  2.73259616e-01
  -2.75222621e-01  3.71258971e-02]]


#### 59. How to sort an array by the nth column? (★★☆)

In [12]:
answer(59)

# Author: Steve Tjoa

Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])


In [13]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[2 9 9]
 [2 7 3]
 [0 2 0]]
[[0 2 0]
 [2 7 3]
 [2 9 9]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [15]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [18]:
answer(61)

Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [19]:
answer(62)

A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])


#### 63. Create an array class that has a name attribute (★★☆)

In [21]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

In [22]:
Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [23]:
answer(64)

# Author: Brett Olsen

Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)


In [25]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)

Z += np.bincount(I, minlength=len(Z))
print(Z)

[6. 2. 4. 5. 1. 2. 2. 3. 2. 3.]


In [27]:
I

array([5, 0, 9, 7, 7, 0, 1, 3, 9, 2, 3, 0, 0, 2, 0, 3, 6, 2, 3, 8])

In [26]:
np.bincount(I)

array([5, 1, 3, 4, 0, 1, 1, 2, 1, 2], dtype=int64)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [30]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [2]:
answer(66)

# Author: Nadav Horesh

w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [21]:
Z = np.random.random((10, 20, 30, 40))
summed = Z.sum(axis=(-2, -1))
summed2= Z.reshape(Z.shape[:-2] + (-1, )).sum(axis=-1)

np.allclose(summed, summed2)

True

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [22]:
answer(68)

# Author: Jaime Fernández del Río

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())


#### 69. How to get the diagonal of a dot product? (★★★)

In [23]:
answer(69)

# Author: Mathieu Blondel

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)